import streamlit as st
import requests
from utils.assesment_UI import show_result_ui

st.set_page_config(page_title="AI-Powered TB Symptom Checker", layout="wide")

# ---- Header ----
st.markdown("""
<style>
.header {
  background: linear-gradient(90deg, #2b6cb0, #805ad5);
  padding: 18px;
  border-radius: 12px;
  color: white;
  font-weight: 700;
  font-size: 30px;
  text-align: center;
}
.card {
  background: white;
  padding: 18px;
  border-radius: 10px;
  box-shadow: 0 4px 10px rgba(0,0,0,0.06);
  margin-bottom: 16px;
}
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="header">AI-Powered Symptom Checker and Risk Assessment Web App for Tuberculosis</div>', unsafe_allow_html=True)
st.markdown(
    "<h4 style='text-align: center;'>🧾 Fill the details below to get a free TB assessment</h4>", 
    unsafe_allow_html=True
)



# ---- Patient Details ----
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("Patient Details")
col1, col2, col3 = st.columns(3)
with col1:
    name = st.text_input("Full name*")
    age = st.number_input("Age (years)*", min_value=0, max_value=120)
    gender = st.selectbox("Gender", ["Prefer not to say", "Male", "Female", "Other"])
with col2:
    wt = st.number_input("Weight (kg) — optional", min_value=0.0, max_value=300.0, step=0.1)
    ht = st.number_input("Height (cm) — optional", min_value=0.0, max_value=250.0, step=0.1)
    sys_bp = st.number_input("Systolic BP (mmHg) — optional", min_value=0, max_value=300, step=1)
with col3:
    dia_bp = st.number_input("Diastolic BP (mmHg) — optional", min_value=0, max_value=200, step=1)
    temp = st.number_input("Temperature (°F)", min_value=90.0, max_value=110.0, step=0.1,value=98.6)
    rp_rate= st.number_input("Respiratory rate (breaths/min) — optional", min_value=0, max_value=60, step=1)
st.markdown('</div>', unsafe_allow_html=True)

# ---- Risk Factors ----
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("Key Risk Factors")
col_a, col_b = st.columns(2)
with col_a:
    HIV = st.checkbox("HIV positive")
    Diabetes = st.checkbox("Diabetes")
    Smoking = st.checkbox("Smoking")
    Alcohol = st.checkbox("Heavy alcohol use")
with col_b:
    contact_bp = st.checkbox("Recent contact with TB patient")
    history = st.checkbox("History of TB")
    immuno = st.checkbox("On immunosuppressive therapy")
    malnutrition = st.checkbox("Malnutrition (low weight)")
st.markdown('</div>', unsafe_allow_html=True)

# ---- Symptoms ----
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("Symptoms")
col_s1, col_s2 = st.columns(2)
with col_s1:
    cough = st.checkbox("Cough")
    cough_duration = None
    if cough:
        cough_duration = st.selectbox("Cough duration", ["<2 weeks", "2-3 weeks", ">3 weeks"])

    sputum = st.checkbox("Sputum production (phlegm)")
    hemoptysis = st.checkbox("Coughing blood (hemoptysis)")
    fever = st.checkbox("Fever / night sweats")

with col_s2:
    weight_loss = st.checkbox("Unintentional weight loss")
    fatigue = st.checkbox("Fatigue / malaise")
    chest_pain = st.checkbox("Chest pain")
    breath_shortness = st.checkbox("Shortness of breath")

other_symptoms = st.text_area("Other symptoms / notes (optional)")

st.markdown('</div>', unsafe_allow_html=True)

# ---- Additional Info ----
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader("Additional Info")

travel_tb_area = st.checkbox("Recent travel to high TB prevalence area")
living_conditions = st.selectbox(
    "Living conditions",
    ["Unknown", "Normal / not crowded", "Crowded / shared housing", "Homeless / shelters"]
)
st.markdown('</div>', unsafe_allow_html=True)

# ---- Submit Button ----
st.markdown('<div class="card">', unsafe_allow_html=True)


# st.markdown('<div class="card">', unsafe_allow_html=True)

# ---- Footer ----
st.markdown("<hr><center>The outputs are generated by an AI model and may not always be accurate or reliable.  Please do not rely solely on these results for any decisions. Always consult qualified professionals (e.g., doctors, experts) for verification. </center>", unsafe_allow_html=True)



# python -m streamlit run frontend.py



patient_data={

"name" : name,
"age" : age,
"gender" : gender,
"weight" : wt,
"height" : ht,
"systolic BP" : sys_bp,
"diastolic BP" :dia_bp,
"temperature (fahrenheit)" : temp,
"Respiratory rate (breaths/min)" : rp_rate,
"HIV" : HIV,
"Diabetes": Diabetes,
"Smoking": Smoking,
    "Alcohol": Alcohol,
    "Recent contact with TB patient": contact_bp,
    "History of TB": history,
    "On immunosuppressive therapy": immuno,
    "Malnutrition (low weight)": malnutrition,
    "Cough": cough,
    "Cough duration": cough_duration,
    "Sputum production (phlegm)": sputum,
    "Coughing blood (hemoptysis)": hemoptysis,
    "Fever / night sweats": fever,
    "Unintentional weight loss": weight_loss,
    "Fatigue / malaise": fatigue,
    "Chest pain": chest_pain,
    "Shortness of breath": breath_shortness,
    "Other symptoms / notes": other_symptoms,
    "Recent travel to high TB prevalence area": travel_tb_area,
    "Living conditions": living_conditions
}





backend_url = "http://127.0.0.1:8000/process"  # FastAPI endpoint
# backend_url = "http://127.0.0.1:60902/process"  # FastAPI endpoint
# is url par request jayegi frontend se

st.markdown("""
    <style>

    /* Apply custom style to Streamlit button */
    div.stButton > button:first-child {
        background: linear-gradient(90deg, #2b6cb0, #805ad5);
        color: white;
        padding: 14px 60px;
        border: none;
        border-radius: 40px;
        font-size: 20px;
        font-weight: 700;
        cursor: pointer;
        transition: all 0.3s ease;
        box-shadow: 0 8px 22px rgba(0,0,0,0.25);
    }

    div.stButton > button:first-child:hover {
        background: linear-gradient(90deg, #805ad5, #2b6cb0);
        transform: scale(1.05);
        box-shadow: 0 12px 28px rgba(0,0,0,0.35);
    }
    </style>
""", unsafe_allow_html=True)

# Centered button container

if st.button("Submit"):
    if not name or age == 0 :
        st.error("⚠️ Please fill all required fields marked with *")
    
    else:
        try:
            response = requests.post(backend_url, json=patient_data)
            response.raise_for_status()  # raises error for non-200 responses
            # print(response.json())    # directly show backend response
            backend_response_json = response.json()   # directly show backend response
            st.success("Details submitted successfully ✅")

            # Call the modular display function
            show_result_ui(backend_response_json)




        except Exception as e:
            st.error(f" Request failed: {e}")
        








