import streamlit as st
import requests
from utils.assesment_UI import show_result_ui

st.set_page_config(page_title="AI-Powered TB Symptom Checker", layout="wide")

# --- Language Selector (Dynamic Toggle) ---
if "lang" not in st.session_state:
    st.session_state.lang = "English"

language = st.sidebar.selectbox(
    "🌐 Select Language / भाषा चुनें", ["English", "हिन्दी"],
    index=0 if st.session_state.lang == "English" else 1
)
st.session_state.lang = language

# --- Translations Dictionary ---
T = {
    "header": {
        "English": "AI-Powered Symptom Checker and Risk Assessment Web App for Tuberculosis",
        "हिन्दी": "एआई-संचालित क्षय रोग (टीबी) लक्षण और जोखिम मूल्यांकन वेब ऐप"
    },
    "subheader": {
        "English": "🧾 Fill the details below to get a free TB assessment",
        "हिन्दी": "🧾 नीचे दिए गए विवरण भरें ताकि आपको मुफ्त टीबी मूल्यांकन मिल सके"
    },
    "patient_details": {"English": "Patient Details", "हिन्दी": "रोगी विवरण"},
    "name": {"English": "Full name*", "हिन्दी": "पूरा नाम*"},
    "age": {"English": "Age (years)*", "हिन्दी": "आयु (वर्षों में)*"},
    "gender": {"English": "Gender", "हिन्दी": "लिंग"},
    "weight": {"English": "Weight (kg) — optional", "हिन्दी": "वज़न (किग्रा) — वैकल्पिक"},
    "height": {"English": "Height (cm) — optional", "हिन्दी": "ऊँचाई (सेमी) — वैकल्पिक"},
    "temp": {"English": "Temperature (°F)", "हिन्दी": "तापमान (°F)"},
    "risk_factors": {"English": "Key Risk Factors", "हिन्दी": "मुख्य जोखिम कारक"},
    "symptoms": {"English": "Symptoms", "हिन्दी": "लक्षण"},
    "additional_info": {"English": "Additional Info", "हिन्दी": "अतिरिक्त जानकारी"},
    "submit": {"English": "Submit", "हिन्दी": "जमा करें"},
    "error": {
        "English": "⚠️ Please fill all required fields marked with *",
        "हिन्दी": "⚠️ कृपया * वाले सभी आवश्यक फ़ील्ड भरें"
    },
    "success": {
        "English": "✅ Details submitted successfully!",
        "हिन्दी": "✅ विवरण सफलतापूर्वक जमा किया गया!"
    },
    "footer": {
        "English": "The outputs are generated by an AI model and may not always be accurate or reliable. Always consult a doctor.",
        "हिन्दी": "परिणाम एआई मॉडल द्वारा उत्पन्न किए गए हैं और हमेशा सटीक नहीं हो सकते। कृपया डॉक्टर से परामर्श अवश्य करें।"
    }
}

# --- Styles ---
st.markdown("""
<style>
.header {
  background: linear-gradient(90deg, #2b6cb0, #805ad5);
  padding: 18px;
  border-radius: 12px;
  color: white;
  font-weight: 700;
  font-size: 30px;
  text-align: center;
}
.card {
  background: white;
  padding: 18px;
  border-radius: 10px;
  box-shadow: 0 4px 10px rgba(0,0,0,0.06);
  margin-bottom: 16px;
}
</style>
""", unsafe_allow_html=True)

# --- Header ---
st.markdown(f"<div class='header'>{T['header'][language]}</div>", unsafe_allow_html=True)
st.markdown(f"<h4 style='text-align:center'>{T['subheader'][language]}</h4>", unsafe_allow_html=True)

# --- Patient Details ---
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader(T["patient_details"][language])
col1, col2, col3 = st.columns(3)
with col1:
    name = st.text_input(T["name"][language])
    age = st.number_input(T["age"][language], min_value=0, max_value=120)
    gender = st.selectbox(T["gender"][language], ["Prefer not to say", "Male", "Female", "Other"])
with col2:
    wt = st.number_input(T["weight"][language], min_value=0.0, max_value=300.0, step=0.1)
    ht = st.number_input(T["height"][language], min_value=0.0, max_value=250.0, step=0.1)
    sys_bp = st.number_input("Systolic BP (mmHg)", min_value=0, max_value=300, step=1)
with col3:
    dia_bp = st.number_input("Diastolic BP (mmHg)", min_value=0, max_value=200, step=1)
    temp = st.number_input(T["temp"][language], min_value=90.0, max_value=110.0, step=0.1, value=98.6)
st.markdown('</div>', unsafe_allow_html=True)

# --- Risk Factors ---
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader(T["risk_factors"][language])
col_a, col_b = st.columns(2)
with col_a:
    HIV = st.checkbox("HIV positive")
    Diabetes = st.checkbox("Diabetes")
    Smoking = st.checkbox("Smoking")
    Alcohol = st.checkbox("Heavy alcohol use")
with col_b:
    contact_bp = st.checkbox("Recent contact with TB patient")
    history = st.checkbox("History of TB")
    immuno = st.checkbox("On immunosuppressive therapy")
    malnutrition = st.checkbox("Malnutrition (low weight)")
st.markdown('</div>', unsafe_allow_html=True)

# --- Symptoms ---
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader(T["symptoms"][language])
col_s1, col_s2 = st.columns(2)
with col_s1:
    cough = st.checkbox("Cough")
    cough_duration = None
    if cough:
        cough_duration = st.selectbox("Cough duration", ["<2 weeks", "2-3 weeks", ">3 weeks"])
    sputum = st.checkbox("Sputum production (phlegm)")
    hemoptysis = st.checkbox("Coughing blood (hemoptysis)")
with col_s2:
    fever = st.checkbox("Fever / night sweats")
    weight_loss = st.checkbox("Unintentional weight loss")
    fatigue = st.checkbox("Fatigue / malaise")
    chest_pain = st.checkbox("Chest pain")
    breath_shortness = st.checkbox("Shortness of breath")
st.markdown('</div>', unsafe_allow_html=True)

# --- Additional Info ---
st.markdown('<div class="card">', unsafe_allow_html=True)
st.subheader(T["additional_info"][language])
travel_tb_area = st.checkbox("Recent travel to high TB prevalence area")
living_conditions = st.selectbox("Living conditions", ["Unknown", "Normal / not crowded", "Crowded / shared housing", "Homeless / shelters"])
st.markdown('</div>', unsafe_allow_html=True)

# --- Data Dictionary ---
patient_data = {
    "name": name, "age": age, "gender": gender, "weight": wt, "height": ht,
    "systolic BP": sys_bp, "diastolic BP": dia_bp, "temperature": temp,
    "HIV": HIV, "Diabetes": Diabetes, "Smoking": Smoking, "Alcohol": Alcohol,
    "Recent contact with TB patient": contact_bp, "History of TB": history,
    "On immunosuppressive therapy": immuno, "Malnutrition (low weight)": malnutrition,
    "Cough": cough, "Cough duration": cough_duration, "Sputum production": sputum,
    "Coughing blood": hemoptysis, "Fever": fever, "Weight loss": weight_loss,
    "Fatigue": fatigue, "Chest pain": chest_pain, "Breath shortness": breath_shortness,
    "Travel": travel_tb_area, "Living conditions": living_conditions
}

backend_url = "http://127.0.0.1:8000/process"

# --- Submit Button ---
st.markdown("""
    <style>
    div.stButton > button:first-child {
        background: linear-gradient(90deg, #2b6cb0, #805ad5);
        color: white; padding: 14px 60px; border-radius: 40px;
        font-size: 20px; font-weight: 700;
        transition: 0.3s ease; box-shadow: 0 8px 22px rgba(0,0,0,0.25);
    }
    div.stButton > button:first-child:hover {
        background: linear-gradient(90deg, #805ad5, #2b6cb0);
        transform: scale(1.05);
    }
    </style>
""", unsafe_allow_html=True)

if st.button(T["submit"][language]):
    if not name or age == 0:
        st.error(T["error"][language])
    else:
        try:
            response = requests.post(backend_url, json=patient_data)
            response.raise_for_status()
            data = response.json()
            st.success(T["success"][language])
            show_result_ui(data)
        except Exception as e:
            st.error(f"Request failed: {e}")

# --- Footer ---
st.markdown(f"<hr><center>{T['footer'][language]}</center>", unsafe_allow_html=True)
